DROP TABLE AspNetRoles
DROP TABLE AspNetUserClaims
DROP TABLE AspNetUserLogins
DROP TABLE AspNetUserRoles
DROP TABLE AspNetUsers
DROP TABLE CommentLists
DROP TABLE Panoptoes
DROP TABLE Comments
DROP TABLE Files
DROP TABLE Folders
DROP TABLE VoteLists
DROP TABLE Votes
DROP TABLE __MigrationHistory
DROP TABLE Comm