using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CollaborativeBath.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit https://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    /// <summary>
    /// Scaffolding file generated by .Net MVC.
    /// Addition commented public properties added by George Andrews
    /// </summary>
    /// <seealso cref="Microsoft.AspNet.Identity.EntityFramework.IdentityUser" />
    public class ApplicationUser : IdentityUser
    {
        /// <summary>
        /// Gets or sets the subscribed folders.
        /// </summary>
        /// <value>
        /// The subscribed folders.
        /// </value>
        public ICollection<Folder> SubscribedFolders { get; set; } = new List<Folder>();
        /// <summary>
        /// Gets or sets the profile image.
        /// </summary>
        /// <value>
        /// The profile image.
        /// </value>
        public byte[] ProfileImage { get; set; }
        /// <summary>
        /// Gets or sets the notifications.
        /// </summary>
        /// <value>
        /// The notifications.
        /// </value>
        public ICollection<Notification> Notifications { get; set; } = new List<Notification>();
        /// <summary>
        /// Gets or sets the subscribed comment lists.
        /// </summary>
        /// <value>
        /// The subscribed comment lists.
        /// </value>
        public ICollection<CommentList> SubscribedCommentLists { get; set; } = new List<CommentList>();
        /// <summary>
        /// Gets or sets the subscribed votelists.
        /// </summary>
        /// <value>
        /// The subscribed votelists.
        /// </value>
        public ICollection<VoteList> SubscribedVotelists { get; set; } = new List<VoteList>();

        //ASP Generated Code
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DbConnection", throwIfV1Schema: false)
        {
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}